apiVersion: v1
data:
  mapRoles: |
    - rolearn: aarn:aws:iam::721233634467:role/eksctl-demo-cluster-1-cluster-ServiceRole-VO4pigMsHkAG
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::721233634467:role/service-role/codebuild-Webapp-project-dev-service-role
      username: build
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::721233634467:user/om
      username: altamash
      groups:
        - system:masters
